env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "x64"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    skip: true

snapshot:
  version_template: "{{ .Tag }}"

