# version format
version: 0.2.{build}

build: false

clone_folder: /appveyor/projects/src/godatastruct

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  GOPATH: /appveyor/projects/

install:
  - go version
  - go env
  - go get -u "gonum.org/v1/gonum/graph"
  - go get -u "github.com/stretchr/testify/assert"

stack: go 1.14

build_cloud: EGOROFF Docker
image: Ubuntu

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic godatastruct/...

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.txt" -t $env:CODECOV_TOKEN

