# version format
version: 0.6.0.{build}

build: false

clone_folder: /appveyor/projects/src/godatastruct

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

install:
  - export GOPATH=/appveyor/projects/
  - sudo chmod ugo+rwx /appveyor/projects/src/
  - sudo chmod ugo+rwx /appveyor/projects/
  - go version
  - go env

stack: go 1.15

image: Ubuntu

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_test:
  - ps: |
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.txt" -t $env:CODECOV_TOKEN

